baseURL = "http://heidiwilliamsfoy.space/"
languageCode = "en-us"
title = "Heidi Williams-Foy"
subtitle = "I am a web developer and general creative person based in Brooklyn, NY. I also like to read and eat Asian food."
theme = "oysterTheme"
paginate = 5
summaryLength = 30
defaultContentLanguage = "en"
canonifyUrls = true

math = true

[params]
  images = ["hwf.png"]
  googleAnalytics = "UA-144509840-1"


[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3
  # [[menu.main]]
    # name = "Resume"
    # pre = "resume"
    # url = "/resume/"
    # weight = 4
  [[menu.main]]
    name = "LinkedIn"
    pre = "LinkedIn"
    url = "https://www.linkedin.com/in/heidiwilliamsfoy/"
    weight = 5

  [params.profile]
     enable = true
     name = "Heidi Williams-Foy"
     tagline = "Senior Technical Account Manager"
     avatar = "avatar.png"

